query GenesisContributors($id: String!) {
  genesisContributors(where: {contributor: $id}) {
    contributor
    totalContribtuionInWei
    firstContributedTimestamp
    lastContributedTimestamp
  }
}
